import type { Metadata } from "next";

import Navigation from "@/components/pages/Navbar";
import Navbar from "@/components/shared/Gennextfooter";
// import Footer from "@/components/shared/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dasboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
    
          <Navigation />
          {children}
          <Navbar />
        
      </body>
    </html>
  );
}
